<?php
use TaxJar\Client;

/**
 * Created by PhpStorm.
 * User: BMcClure
 * Date: 3/16/2016
 * Time: 5:15 PM
 */

function commerce_tax_services_taxjar_tax_service_info() {
  $tax_services = array();

  $tax_services['taxjar'] = array(
    'name' => t('TaxJar'),
    'module' => 'commerce_tax_services_taxjar',
  );

  return $tax_services;
}

function commerce_tax_services_taxjar_tax_service_calculate($order, $variables) {
  $api_key = variable_get('commerce_tax_services_taxjar_api_key', false);

  if (!$api_key) {
    return false;
  }

  // Build order wrapper.
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

  $sales_tax = array(
    'amount' => 0,
    'currency_code' => $variables['currency_code'],
    'data' => array(),
  );

  try {
    $taxjar = Client::withApiKey($api_key);

    $order_total = $order_wrapper->commerce_order_total;

    $order_taxes = $taxjar->taxForOrder([
      'from_country' => $variables['primary_country'],
      'from_zip' => $variables['primary_zip'],
      'from_state' => $variables['primary_state'],
      'to_country' => $variables['country'],
      'to_zip' => $variables['zip'],
      'to_state' => $variables['state'],
      'amount' => commerce_currency_amount_to_decimal($order_total->amount->value(), $order_total->currency_code->value()),
      'shipping' => commerce_tax_services_get_shipping_price($order),
    ]);

    $tax_amount = $order_taxes->amount_to_collect;

    if ($tax_amount > 0) {
      $sales_tax['amount'] = commerce_currency_decimal_to_amount($tax_amount, $order_total->currency_code->value());
    }
  } catch (Exception $e) {
    drupal_set_message("TaxJar error: " . $e->getMessage());
  }

  return $sales_tax;
}

function commerce_tax_services_taxjar_tax_service_admin_options($form, $form_state) {
  $options = array();

  $options['commerce_tax_services_taxjar_api_key'] = array(
    '#title' => t('TaxJar API Key'),
    '#description' => t('The API key for the TaxJar account to utilize for requests to the TaxJar service'),
    '#type' => 'textfield',
    '#default_value' => variable_get('commerce_tax_services_taxjar_api_key', false),
  );

  return $options;
}
